### ISSUE TITLE
Add License and Project Admin in Readme File

### ISSUE THREAD

**Issue by Shaishav0507** [kashish-ag/Detection-of-Plant-Disease#14]
Hey @kashish-ag @niranjanstudy06 
I would like to add License and Project admin in readme file.
Please assign it to me.
Thanks.

**Comment by kashish-ag** [comment]
I think it already has those things.

**Comment by Shaishav0507** [comment]
It's there in the branch but not linked in the readme file.

**Comment by kashish-ag** [comment]
Okay sure work on it :)

**Comment by kashish-ag** [comment]
I have accepted the PR. Thankyou:)

**Comment by Shaishav0507** [comment]
Thank you @kashish-ag
