### ISSUE TITLE
Update Readme and Code of Conduct

### ISSUE THREAD

**Issue by kashish-ag** [kashish-ag/Detection-of-Plant-Disease#16]
This is to update the readme and Code of Conduct.

**Comment by Baba-Yaga-1** [comment]
I would like to work on this issue by updating the README.md file with the contributors, the tech stacks and also the Code of Conduct. Can you assign it to me ?

**Comment by kashish-ag** [comment]
Sure:)

**Comment by Ayan-thecodeking** [comment]
hey @kashish-ag  please assign me also ...atleast for one of this 
i'll do code of conduct 

plz plz plz :)

**Comment by kashish-ag** [comment]
Ayan can you add the admins section in the readme? If yes, I'll open that issue

**Comment by Ayan-thecodeking** [comment]
> Ayan can you add the admins section in the readme? If yes, I'll open that issue

Ya sure I'll add that @kashish-ag 
Thanks a lot :)
Assign me

**Comment by Ayan-thecodeking** [comment]
hey @kashish-ag  u haven't assigned me ???

**Comment by kashish-ag** [comment]
Ayan I have opened a new issue. Please comment there.

**Comment by kashish-ag** [comment]
Thanks @LizaHaddock I have accepted the PR
