### ISSUE TITLE
add contributing guidelines in readme

### ISSUE THREAD

**Issue by Ayan-thecodeking** [kashish-ag/Detection-of-Plant-Disease#19]
hey @kashish-ag   I want to add contributing guidelines  in readme ...that will consist all the steps required during contributing 
hope u got it 
please assign me for this 
thanks :)

**Comment by kashish-ag** [comment]
Ayan also with that can you update the readme in a better way? As you can see some things are repetitive and some need to be represented in a better way. So can you do a final addition to readme in all its sections?

**Comment by Ayan-thecodeking** [comment]
> Ayan also with that can you update the readme in a better way? As you can see some things are repetitive and some need to be represented in a better way. So can you do a final addition to readme in all its sections?

ya sure @kashish-ag i'll do it ...
going to update very sooon :)
thanks 
please assign me now for this

**Comment by kashish-ag** [comment]
Sure :)
