### ISSUE TITLE
Add open source section

### ISSUE THREAD

**Issue by rishabhrathore055** [kashish-ag/Detection-of-Plant-Disease#23]

**Comment by rishabhrathore055** [comment]
@kashish-ag pls assign me this issue

**Comment by kashish-ag** [comment]
Please tell me what you want to do

**Comment by rishabhrathore055** [comment]
@kashish-ag  column to represent that this project is a part of lgm-soc'21

**Comment by kashish-ag** [comment]
Rishabh I don't think it is needed

**Comment by rishabhrathore055** [comment]
@kashish-ag but this project is under LGM-SOC'21 right?

**Comment by kashish-ag** [comment]
Yes, it is.

**Comment by rishabhrathore055** [comment]
So i think open source section must show that this project is under LGM-Soc21 and  for the further Open source programs

**Comment by kashish-ag** [comment]
But I have already assigned someone to edit the final readme
