### ISSUE TITLE
Add LGM-SOC'21 score card in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [kashish-ag/Detection-of-Plant-Disease#24]
Add LGM-SOC'21 score card in readme.md

**Comment by ishitakapoor26** [comment]
Add LGM-SOC'21 score card in readme.md

**Comment by ishitakapoor26** [comment]
@kashish-ag pls assign me this issue.

**Comment by kashish-ag** [comment]
Ishita can you please elaborate what will scorecard consist?

**Comment by ishitakapoor26** [comment]
> Ishita can you please elaborate what will scorecard consist?

@kashish-ag here is ss.
![score card](https://user-images.githubusercontent.com/78542333/122349110-8aac5e80-cf69-11eb-8616-c362000388ac.PNG)

**Comment by kashish-ag** [comment]
Sure add it :)
