### ISSUE TITLE
add some badges to README

### ISSUE THREAD

**Issue by Umesh-01** [kashish-ag/Detection-of-Plant-Disease#28]
### Description
add badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

![image](https://user-images.githubusercontent.com/83420185/122651493-d112e080-d156-11eb-87e7-e651700795d9.png)

### Solution
I will add some badges and also will add links related to them to the top so that the README.md file will look more interactive and awesome.

### Working under/as
- [x] LGMSOC
- [ ] Contributor

**Comment by Umesh-01** [comment]
@kashish-ag should I make these changes??

**Comment by kashish-ag** [comment]
Sure Umesh.

**Comment by bhavesh-jo** [comment]
Can I work on this also can there be multiple badges ?
