### ISSUE TITLE
I have an idea about the project as

### ISSUE THREAD

**Issue by Komal-99** [kashish-ag/Detection-of-Plant-Disease#31]
preparing a model to detect disease we can for making a git hub page for the same , as git hub repo look very like technical people can easily understood and access it by website like a page for  project idea one for methodology behind the source code and implementation .
I a not much aware how to implement it but have basic knowledge and we can try giving it a start then more issue can be created as per need and features like animation and all can be added.

**Comment by kashish-ag** [comment]
I guess this would need a lot of time and skills and as I am not much into web development I guess you'll need to complete it alone. If you think you can make it all by yourself, please revert I'll assign this issue.

**Comment by Komal-99** [comment]
Yes I can do basic ans slowly to advance as learning web dev , elsewhere you can ask about this feature in  discord channel so that other can also help mw

**Comment by kashish-ag** [comment]
I guess it would need more time and attention even after this program, so let's keep it for some time else. By the way, I have created a new issue for your readme idea please comment there one.
