### ISSUE TITLE
Add Code Of conduct and Contributing Guidelines 

### ISSUE THREAD

**Issue by Akash20x** [kashish-ag/Detection-of-Plant-Disease#4]
I want to add Code of conduct.md and contributing.md file for your repository.

Kindly assign me this issue as a part of LGM-SOC'21.

**Comment by harshita9621** [comment]
Hii,  I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by Rockzzzz-221** [comment]
I want to add Code of conduct.md and contributing.md file for your repository under LGM-SOC'21. Pleasee assign me to do so.

**Comment by jayant766** [comment]
Please assign me this issue under LGMSOC'21

**Comment by kashish-ag** [comment]
I have assigned it for now. You can open new issues by seeing the description on slack. I'll add more shortly.

**Comment by kashish-ag** [comment]
Thanks Akash :)
