### ISSUE TITLE
Add more data-set

### ISSUE THREAD

**Issue by kashish-ag** [kashish-ag/Detection-of-Plant-Disease#5]
This issue is for adding more data-set to the model. You can add a new data set or update the existing one.

**Comment by nekkantimadhu** [comment]
I would like to contribute on this issue under LGM SOC 21, Could you please assign this issue to me?

**Comment by kashish-ag** [comment]
Yes sure :)

**Comment by PaliwalUmesh** [comment]
I would like to contribute @kashish-ag ,  assign please.

**Comment by kashish-ag** [comment]
I have already assigned it @PaliwalRP.

**Comment by PaliwalUmesh** [comment]
ohh okay.
