### ISSUE TITLE
Set up Frontend code

### ISSUE THREAD

**Issue by kashish-ag** [kashish-ag/Detection-of-Plant-Disease#6]
This issue is for contributors willing to contribute in web dev/app dev + python. Develop a code for the frontend using any language/framework you want (flask/Django/HTML/CSS) with backend as python.

**Comment by vaibhavgupta2499** [comment]
Can I make (html + flask) form like structure for frontend.

**Comment by kashish-ag** [comment]
Ya sure :)

**Comment by vaibhavgupta2499** [comment]
I have made a Pull request regarding this issue. Kindly please check and revert back with suggestions and issues.

Edit 1: Please count this as I am a participant in LGM-SOC participant.

**Comment by kashish-ag** [comment]
It's satisfactory Vaibhav Thank you so much! I have merged it :)
